### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by mijicd** [zio/zio-nio#7]
Currently, the tests are failing with the following error:

```
[info] Running zio.nio.Main                                                                                                                                          [203/539]
Fiber failed.                                                                                                                                                                 
A checked error was not handled.                                                                                                                                              
java.lang.NullPointerException                                                                                                                                                
        at zio.nio.channels.AsynchronousChannelGroup.$anonfun$awaitTermination$1(AsynchronousChannelGroup.scala:44)                                                           
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)                                                                                             
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:410)                                                                                                      
        at zio.Runtime.unsafeRunAsync(Runtime.scala:93)                                                                                                                       
        at zio.Runtime.unsafeRunAsync$(Runtime.scala:79)                                                                                                                      
        at zio.nio.AsynchronousChannelGroupSuite$.unsafeRunAsync(AsynchronousChannelGroupSuite.scala:17)                                                                      
        at zio.Runtime.unsafeRunSync(Runtime.scala:68)                                                                                                                        
        at zio.Runtime.unsafeRunSync$(Runtime.scala:65)                                                                                                                       
        at zio.nio.AsynchronousChannelGroupSuite$.unsafeRunSync(AsynchronousChannelGroupSuite.scala:17)                                                                       
        at zio.nio.AsynchronousChannelGroupSuite$.$anonfun$tests$9(AsynchronousChannelGroupSuite.scala:74)                                                                    
        at org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:21)                                                                                                
        at org.specs2.matcher.Expectable.value(Expectable.scala:21)                                                                                                           
        at org.specs2.matcher.OptionLikeMatcher.$anonfun$apply$7(OptionMatchers.scala:69)                                                                                     
        at org.specs2.matcher.Matcher.result(Matcher.scala:44)                                                                                                                
        at org.specs2.matcher.Matcher.result$(Matcher.scala:43)                                                                                                               
        at org.specs2.matcher.OptionLikeMatcher.result(OptionMatchers.scala:67)                                                                                               
        at org.specs2.matcher.OptionLikeMatcher.apply(OptionMatchers.scala:69)                                                                                                
        at org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:51)                                                                                                    
        at org.specs2.matcher.MustExpectable.must(MustExpectable.scala:16)                                                                                                    
        at zio.nio.AsynchronousChannelGroupSuite$.$anonfun$tests$8(AsynchronousChannelGroupSuite.scala:75)                                                                    
        at org.specs2.matcher.MatchResultImplicits.fromMatchResult(MatchersImplicits.scala:47)                                                                                
        at org.specs2.matcher.MatchResultImplicits.fromMatchResult$(MatchersImplicits.scala:47)                                                                               
        at zio.nio.AsynchronousChannelGroupSuite$.fromMatchResult(AsynchronousChannelGroupSuite.scala:17)
        at zio.nio.AsynchronousChannelGroupSuite$.$anonfun$tests$7(AsynchronousChannelGroupSuite.scala:75)
        at testz.FutureHarness$$anon$3.$anonfun$test$4(stdlib.scala:141)
        at testz.FutureHarness$$anon$3.$anonfun$bracket$4(stdlib.scala:193)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 

Fiber:816 was supposed to continue to:
  a future continuation at zio.nio.AsynchronousChannelGroupSuite$.tests(AsynchronousChannelGroupSuite.scala:73)

Fiber:816 execution trace:
  at zio.ZIO.refineOrDieWith(ZIO.scala:717) 
  at zio.nio.channels.AsynchronousChannelGroup.awaitTermination(AsynchronousChannelGroup.scala:44)

Fiber:816 was spawned by: <empty trace>
Fiber failed.
```

To make things a bit worse, CircleCI builds for #6 are green even though the failure is there.

**Comment by quelgar** [comment]
I'm not sure this is a bug, per se. For example, `AsynchronousChannelGroupSuite` has the code `new AsynchronousChannelGroup(null)`, which seems designed to test error recovery by deliberately inducing an NPE to crash the fibre.

Having said that, it would be great if such tests could work without outputting a bunch of diagnostics which make it look like something has gone horribly wrong. I'm not sure off the top of my head what's the best way to do that.

**Comment by pshemass** [comment]
I agree with @quelgar this is not test failing is just output with exception printed to stdout

**Comment by mijicd** [comment]
Well, I disagree that it's not the failing test. As you can see [here](https://circleci.com/gh/zio/zio-nio/68?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) it can cause test timeouts, thus failures. 

I understand the point stated above, but nevertheless we should either express it differently or solve the existing problem. No need for flaky tests :).

**Comment by pshemass** [comment]
@mijicd you are right because bad usage of fork and join test was not deterministic - sometimes fail with of connection refuse because server wasn't ready yet, sometime hangs because bind but not accept yet, sometime pass. 

I fixed that in my PR https://github.com/zio/zio-nio/pull/12

**Comment by pshemass** [comment]
@mijicd we should close this
